enforce scripts to be run as root

diff --git a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
--- a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
+++ b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
@@ -17,6 +17,14 @@
 [ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
 set -e
 
+# Enforce root rights
+#
+if [[ ${EUID} -ne 0 ]];
+	then
+	echo "ERROR: $0 needs to be run as root. Aborting ..."
+	exit 1
+fi
+
 if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
 	then
 	LIVE=true
diff --git a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
--- a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
+++ b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
@@ -17,6 +17,14 @@
 IPS="`/bin/hostname -I`"
 FQDN="`/bin/hostname -f`"
 
+# Enforce root rights
+#
+if [[ ${EUID} -ne 0 ]];
+	then
+	echo "ERROR: $0 needs to be run as root. Aborting ..."
+	exit 1
+fi
+
 # Read GS version from database and update local config file
 #
 if [ -f "${GS_MYSQL_PASSWORD_FILE}" ]; then
diff --git a/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init b/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init
--- a/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init
+++ b/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init
@@ -13,6 +13,14 @@
 # General settings
 [ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
 
+# Enforce root rights
+#
+if [[ ${EUID} -ne 0 ]];
+	then
+	echo "ERROR: $0 needs to be run as root. Aborting ..."
+	exit 1
+fi
+
 case "$1" in
 start)
 	FQDN="`hostname -f`";
diff --git a/config.v2/chroot_local-includes/etc/init.d/iptables-persistent b/config.v2/chroot_local-includes/etc/init.d/iptables-persistent
--- a/config.v2/chroot_local-includes/etc/init.d/iptables-persistent
+++ b/config.v2/chroot_local-includes/etc/init.d/iptables-persistent
@@ -16,6 +16,14 @@ then
         . /etc/iptables/iptables.conf
 fi
 
+# Enforce root rights
+#
+if [[ ${EUID} -ne 0 ]];
+	then
+	echo "ERROR: $0 needs to be run as root. Aborting ..."
+	exit 1
+fi
+
 case "$1" in
 start)
     if [ -e /var/run/iptables ]; then
diff --git a/config.v2/chroot_local-includes/etc/init.d/mon_ami b/config.v2/chroot_local-includes/etc/init.d/mon_ami
--- a/config.v2/chroot_local-includes/etc/init.d/mon_ami
+++ b/config.v2/chroot_local-includes/etc/init.d/mon_ami
@@ -27,6 +27,14 @@ DEBUG=""
 ARGS="--log-file=/var/log/mon_ami/mon_ami.log ${DEBUG}"
 USER="mon_ami"
 
+# Enforce root rights
+#
+if [[ ${EUID} -ne 0 ]];
+	then
+	echo "ERROR: $0 needs to be run as root. Aborting ..."
+	exit 1
+fi
+
 if ! [ -x $DAEMON ] ; then
 	echo "ERROR: $DAEMON not found"
 	exit 1
