introduce global configuration file & improved file permissons management

diff --git a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
--- a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
+++ b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-init
@@ -14,9 +14,8 @@
 # General settings
 [ -f /gdfdl.conf ] && source /gdfdl.conf
 [ -f /gdfdl-custom.conf ] && source /gdfdl-custom.conf
+[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
 set -e
-
-GS_DIR_LOCAL="/var/opt/gemeinschaft"
 
 if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
 	then
@@ -100,8 +99,6 @@ OPTION       = 67108864
 USER         = gemeinschaft
 PASSWORD     = ${MYSQL_PASSWD_GS}
 " >/var/lib/freeswitch/.odbc.ini
-chmod 644 /var/lib/freeswitch/.odbc.ini
-chown freeswitch.freeswitch /var/lib/freeswitch/.odbc.ini
 
 		# (re)create Gemeinschaft database
 		echo "** Creating MySQL database 'gemeinschaft'"
@@ -113,14 +110,13 @@ chown freeswitch.freeswitch /var/lib/freeswitch/.odbc.ini
 
 		# Update database password in FreeSwitch configs
 		echo "** Updating FreeSwitch with new MySQL password"
-		sed -i "s/password =.*/password = ${MYSQL_PASSWD_GS}/" "${GS_DIR_LOCAL}/freeswitch/scripts/ini/database.ini"
-		sed -i "s/odbc-dsn =.*/odbc-dsn = gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}/" "${GS_DIR_LOCAL}/freeswitch/scripts/ini/sofia.ini"
-		sed -i "s/<param name=\"core-db-dsn\".*/<param name=\"core-db-dsn\" value=\"gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}\"\/>/" "${GS_DIR_LOCAL}/freeswitch/conf/freeswitch.xml"
-		sed -i "s/<param name=\"odbc-dsn\".*/<param name=\"odbc-dsn\" value=\"gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}\"\/>/" "${GS_DIR_LOCAL}/freeswitch/conf/freeswitch.xml"
+		sed -i "s/password =.*/password = ${MYSQL_PASSWD_GS}/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/database.ini"
+		sed -i "s/odbc-dsn =.*/odbc-dsn = gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/sofia.ini"
+		sed -i "s/<param name=\"core-db-dsn\".*/<param name=\"core-db-dsn\" value=\"gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}\"\/>/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/conf/freeswitch.xml"
+		sed -i "s/<param name=\"odbc-dsn\".*/<param name=\"odbc-dsn\" value=\"gemeinschaft:gemeinschaft:${MYSQL_PASSWD_GS}\"\/>/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/conf/freeswitch.xml"
 
 		# Lower debug levels for productive installations
-		[ -f /etc/gdfdl_build ] && BUILD=`cat /etc/gdfdl_build` || BUILD=1234567890
-		if [[ `expr length ${BUILD}` == 10 ]]; then
+		if [[ `expr length ${GS_BUILDNAME}` == 10 ]]; then
 			/usr/local/bin/gs-change-state.sh production
 
 		# Enforce higher debug levels for development installations
diff --git a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
--- a/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
+++ b/config.v2/chroot_local-includes/etc/init.d/gdfdl-custom-prompt
@@ -12,18 +12,21 @@
 # Create customized login screen for Gemeinschaft 5
 #
 
+# General settings
+[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
 IPS="`/bin/hostname -I`"
 FQDN="`/bin/hostname -f`"
-GDFDL_BUILDNAME="`cat /etc/gdfdl_build`"
-GS_BRANCH="`cat /etc/gemeinschaft_branch`"
 
-# Read GS version from database
+# Read GS version from database and update local config file
 #
-if [ -f /var/lib/gs5/.gs_mysql_password ]; then
-	MYSQL_PASSWD="`cat /var/lib/gs5/.gs_mysql_password`"
-	GEMEINSCHAFT_VERSION=$(mysql --skip-column-names -e "SELECT value FROM gs_parameters WHERE name = 'GEMEINSCHAFT_VERSION';" --user=gemeinschaft --password="${MYSQL_PASSWD}" gemeinschaft || echo "5.x")
+if [ -f "${GS_MYSQL_PASSWORD_FILE}" ]; then
+	MYSQL_PASSWD="`cat ${GS_MYSQL_PASSWORD_FILE}`"
+	GS_VERSION=$(mysql --skip-column-names -e "SELECT value FROM gs_parameters WHERE name = 'GEMEINSCHAFT_VERSION';" --user=${GS_MYSQL_USER} --password="${MYSQL_PASSWD}" ${GS_MYSQL_DB} || echo "5.x")
+	mv -f /etc/gemeinschaft/system.conf /etc/gemeinschaft/system.conf.bak
+	grep -Ev ^GS_VERSION= /etc/gemeinschaft/system.conf.bak > /etc/gemeinschaft/system.conf
+	echo "GS_VERSION=\"${GS_VERSION}\"" >> /etc/gemeinschaft/system.conf
 else
-	echo "ERROR: GS lost it's database password in /var/lib/gs5/.gs_mysql_password !"
+	echo "ERROR: GS database password file ${GS_MYSQL_PASSWORD_FILE} not found"
 fi
 
 # Check for live status
@@ -38,8 +41,7 @@ fi
 # Check if we have a production or development state build
 # (production = master-branch was used from GS5 and GBE repo)
 #
-[ -f /etc/gdfdl_build ] && BUILD=`cat /etc/gdfdl_build` || BUILD=1234567890
-if [[ `expr length ${BUILD}` == 10 && x${GS_BRANCH} = x"master" ]]
+if [[ `expr length ${GS_BUILDNAME}` == 10 && x${GS_BRANCH} = x"master" ]]
 	then
 	PRODUCTION=true
 else
@@ -58,9 +60,9 @@ echo "
 
 if [[ ${PRODUCTION} == true ]]
 	then
-	echo "***     Release Version: ${GEMEINSCHAFT_VERSION}.${GDFDL_BUILDNAME}" >> /etc/issue
+	echo "***     Release Version: ${GS_VERSION}.${GS_BUILDNAME}" >> /etc/issue
 else
-	echo "***     Development Version: ${GEMEINSCHAFT_VERSION}-${GS_BRANCH}.${GDFDL_BUILDNAME}" >> /etc/issue
+	echo "***     Development Version: ${GS_VERSION}-${GS_BRANCH}.${GS_BUILDNAME}" >> /etc/issue
 fi
 
 echo "***    -------------------------------------------------------------
@@ -109,13 +111,13 @@ echo "***
 #
 if [[ ${PRODUCTION} == true ]]
 	then
-	echo "Welcome to GEMEINSCHAFT ${GEMEINSCHAFT_VERSION}" > /etc/issue.net
+	echo "Welcome to GEMEINSCHAFT ${GS_VERSION}.${GS_BUILDNAME}" > /etc/issue.net
 echo "
-***   Welcome to GEMEINSCHAFT ${GEMEINSCHAFT_VERSION}" > /etc/motd
+***   Welcome to GEMEINSCHAFT ${GS_VERSION}.${GS_BUILDNAME}" > /etc/motd
 else
-	echo "Welcome to GEMEINSCHAFT ${GEMEINSCHAFT_VERSION}-${GS_BRANCH}" > /etc/issue.net
+	echo "Welcome to GEMEINSCHAFT ${GS_VERSION}-${GS_BRANCH}.${GS_BUILDNAME}" > /etc/issue.net
 echo "
-***   Welcome to GEMEINSCHAFT ${GEMEINSCHAFT_VERSION}-${GS_BRANCH}" > /etc/motd
+***   Welcome to GEMEINSCHAFT ${GS_VERSION}-${GS_BRANCH}.${GS_BUILDNAME}" > /etc/motd
 fi
 
 
diff --git a/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init-post b/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init-post
--- a/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init-post
+++ b/config.v2/chroot_local-includes/etc/init.d/gemeinschaft-runtime-init-post
@@ -10,6 +10,8 @@
 # Description:       Updates certain configurations after reboot to comply with current network settings
 ### END INIT INFO
 
+# General settings
+[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
 
 case "$1" in
 start)
@@ -39,22 +41,24 @@ start)
 		echo "Updating Gemeinschaft configurations ..."
 
 		# Update static files
-		[[ -f /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^phone_book_entry_image_url =.*/phone_book_entry_image_url = http:\/\/${ADDRESS}\/uploads\/phone_book_entry\/image/" /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini
-		[[ -f /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^user_image_url =.*/user_image_url = http:\/\/${ADDRESS}\/uploads\/user\/image/" /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini
-		[[ -f /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^ringtone_url =.*/ringtone_url = http:\/\/${ADDRESS}/" /var/opt/gemeinschaft/freeswitch/scripts/ini/dialplan.ini
+		[[ -f "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini" ]] && sed -i "s/^phone_book_entry_image_url =.*/phone_book_entry_image_url = http:\/\/${ADDRESS}\/uploads\/phone_book_entry\/image/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini"
+		[[ -f "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini" ]] && sed -i "s/^user_image_url =.*/user_image_url = http:\/\/${ADDRESS}\/uploads\/user\/image/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini"
+		[[ -f "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini" ]] && sed -i "s/^ringtone_url =.*/ringtone_url = http:\/\/${ADDRESS}/" "${GS_DIR_NORMALIZED_LOCAL}/freeswitch/scripts/ini/dialplan.ini"
 
 		# Update database settings
-		if [ -f /var/lib/gs5/.gs_mysql_password ];
+		if [ -f "${GS_MYSQL_PASSWORD_FILE}" ];
 			then
-				MYSQL_PASSWD="`cat /var/lib/gs5/.gs_mysql_password`"
-				mysql -e "UPDATE gs_parameters SET value = '127.0.0.1' WHERE name = 'HOMEBASE_IP_ADDRESS';" --user=gemeinschaft --password="${MYSQL_PASSWD}" gemeinschaft
+				MYSQL_PASSWD="`cat "${GS_MYSQL_PASSWORD_FILE}"`"
+				mysql -e "UPDATE gs_parameters SET value = '${ADDRESS}' WHERE name = 'HOMEBASE_IP_ADDRESS';" --user=${GS_MYSQL_USER} --password="${MYSQL_PASSWD}" ${GS_MYSQL_DB}
 		else
-			echo "ERROR: GS lost it's database password in /var/lib/gs5/.gs_mysql_password !"
+			echo "ERROR: GS database password file ${GS_MYSQL_PASSWORD_FILE} not found"
 		fi
 
-
-
 	done
+
+	# Enforce file permissions
+	echo "Enforcing file permissions ..."
+	/usr/local/bin/gs-set-file-permissions.sh
 
 	;;
 *)
